config/routes.rb
Rails.application.routes.draw do
  get 'blogs' => 'blog#index', as: 'blogs'
  get 'blogs/new' => 'blog#new', as: 'new_blog'
  post 'blogs' => 'blog#create'
  get 'blogs/:id' => 'blog#show', as: 'blog'
  get 'blogs/:id/edit' => 'blog#edit', as: 'edit_blog'
  root 'blog#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
    def index
        @blogs = Blog.all 
    end

    def show
        @blogs = Blog.find(params[:id])
    end

    def new
        @blogs = Blog.new
    end

    def create
        @blogs = Blog.create(blog_params)
        if @blogs.valid?
            redirect_to blogs_path
        else
            redirect_to new_blog_path
        end
    end

    def edit
        @blogs = Blog.find(params[:id])
    end

    def update
        @blogs = Blog.find(params[:id])
        @blogs.update(blog_params)
        if @blogs.valid?
            redirect_to blogs_path(@blogs)
        else
            redirect_to edit_blog_path
        end
    end
end

private
def blog_params
    params.require(:blog).permit(:title,:content)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/edit.html.erb
<h2>Update your blog post!</h2>

<%= form_with model: @blogs do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title%>
  <br>
  <br>
  <%= form.label :content %>
  <%= form.text_field :content %>
  <br>
  <br>
  <%= form.submit 'Edit Blog Post' %>
<% end %>
<br>
<%= link_to 'Back to Home', blogs_path %>

app/views/blog/index.html.erb
<h1>Our Blog(s) App</h1>

<ul>
  <% @blogs.each do |blog| %>
    <li>
      <%= link_to blog.title, blog_path(blog) %>
    </li>
  <% end %>
</ul>

<p><%= link_to 'New Blog Post', new_blog_path %></p>

app/views/blog/new.html.erb
<h3>Add a New Blog Post</h3>
<%= form_with model: @blogs, local: true do |form| %>

  <%= form.label :title %>
  <%= form.text_field :title %>

  <br>
  <%= form.label :content %>
  <%= form.text_field :content %>

  <br>
  <%= form.submit 'Add Blog Post' %>
<% end %>

<p><%= link_to 'Home Page', blogs_path %></p>

app/views/blog/show.html.erb
<h3><%= @blogs.title %></h3>
<p><%= @blogs.content %></p>

<%= link_to 'Edit Blog', edit_blog_path(@blogs) %>
<p><%= link_to 'Home Page', blogs_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogPostChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>